steps:
  - label: 'cardano-rt-view-linux-release'
    command: 'nix-build release.nix -A cardano-rt-view-linux-release'
    agents:
      system: x86_64-linux
    artifact_paths:
      - '/tmp/output/*'

  - label: 'cardano-rt-view-win64-release'
    command: 'nix-build release.nix -A cardano-rt-view-win64-release'
    agents:
      system: x86_64-linux
    artifact_paths:
      - '/tmp/output/*'

  - label: 'cardano-rt-view-darwin-release'
    command: 'nix-build release.nix -A cardano-rt-view-darwin-release'
    agents:
      system: x86_64-darwin
